#!/usr/bin/env bash
# ********************************************************************************
# Script: rotate-goods-secrets.sh
# Author: Richard Knechtel
# Description: 
# Rotate the goods application-role passwords (rw + ro per env)
# stored in AWS Secrets Manager, and emit ALTER USER SQL for each env so the
# new passwords can be applied to the matching PostgreSQL roles on the
# ap-{env} Aurora cluster.
#
# Passwords are generated by ./genpassword.sh (complexity 3, length 30).
# AWS calls assume the caller has admin credentials for the account that
# owns these secrets (123456789012). Wrap with Granted:
#
#   assume admin --exec -- bash rotate-goods-secrets.sh \
#     > goods-pw-reset.sql 2> rotate.log
#
# Stdout: SQL blocks grouped by env, ready to paste into psql on each
# ap-{env} cluster as a superuser/master.
# Stderr: progress / error messages.
#
# Existing aws_secretsmanager_secret_version resources in
# terraform-aws-infrastructure/developerdbcreds.tf have been removed
# (Option B), so these put-secret-value calls are the authoritative source
# of password state.
# ********************************************************************************

# *********************************************************************
# Note: 
# Replace: 123456789012
# With your AWS Account Number
# *********************************************************************

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GENPASS="${GENPASS:-$SCRIPT_DIR/genpassword.sh}"
COMPLEXITY="${COMPLEXITY:-3}"
LENGTH="${LENGTH:-30}"

command -v jq  >/dev/null || { echo "ERROR: jq not found" >&2; exit 1; }
command -v aws >/dev/null || { echo "ERROR: aws cli not found" >&2; exit 1; }
[[ -x "$GENPASS" ]]       || { echo "ERROR: not executable: $GENPASS" >&2; exit 1; }

SECRETS=(
  "dev/goods-aurora-readwrite"
  "dev/goods-aurora-readonly"
  "qa/goods-aurora-readwrite"
  "qa/goods-aurora-readonly"
  "staging/goods-aurora-readwrite"
  "staging/goods-aurora-readonly"
  "prod/goods-aurora-readwrite"
  "prod/goods-aurora-readonly"
)

declare -A SQL_BY_ENV=()

for SECRET_ID in "${SECRETS[@]}"; do
  ENV="${SECRET_ID%%/*}"
  echo "→ rotating $SECRET_ID" >&2

  CURRENT_JSON=$(aws secretsmanager get-secret-value \
    --secret-id "$SECRET_ID" --query SecretString --output text)

  USERNAME=$(jq -r '.username' <<< "$CURRENT_JSON")
  [[ -n "$USERNAME" && "$USERNAME" != "null" ]] || {
    echo "  ERROR: could not parse username from $SECRET_ID" >&2; exit 1; }

  NEW_PASS=$("$GENPASS" "$COMPLEXITY" "$LENGTH")
  [[ -n "$NEW_PASS" ]] || { echo "  ERROR: empty password from $GENPASS" >&2; exit 1; }

  NEW_JSON=$(jq --arg pw "$NEW_PASS" '.password = $pw' <<< "$CURRENT_JSON")

  VERSION_ID=$(aws secretsmanager put-secret-value \
    --secret-id "$SECRET_ID" \
    --secret-string "$NEW_JSON" \
    --query VersionId --output text)
  echo "  new AWSCURRENT version: $VERSION_ID" >&2

  # Escape single quotes for safe inclusion in SQL string literals.
  SQL_PASS="${NEW_PASS//\'/\'\'}"
  SQL_BY_ENV[$ENV]+="ALTER USER \"$USERNAME\" WITH PASSWORD '$SQL_PASS';"$'\n'
done

cat <<'BANNER'
-- ============================================================
--  Run each block as a privileged user (e.g. the cluster master)
--  on the corresponding ap-{env} writer endpoint.
-- ============================================================
BANNER

for ENV in dev qa staging prod; do
  echo
  echo "-- ${ENV}  (host: ap-${ENV}.cluster-cwslgsbml112.us-east-1.rds.amazonaws.com)"
  printf '%s' "${SQL_BY_ENV[$ENV]:-}"
done
